website:
    title: AquaCMS
    https: true
    view: App/Views
    controller: App/Controllers
    routes: Routes
    publickey: 
    privatekey: 
    votereward: 10
    rates: { exp: 500, penya: 500, drop: 500 }
    sidebar: { user_online: true, user_peak: true }
database:
    server: .\SQLEXPRESS
    username: sa
    password: 
    account_dbf: ACCOUNT_DBF
    character_dbf: CHARACTER_01_DBF
    logging_dbf: LOGGING_01_DBF
    website_dbf: WEB_DBF
    item_dbf: ITEM_DBF
server:
    salt: kikugalanet
    ip: 127.0.0.1
    port: 5600
shop:
    param1: 0
    param2: 0
security:
    admin: Z
    gamemaster: G
    user: F
0:
    security.user: H
