USE [WEB_DBF]
GO

/****** Object:  Table [dbo].[WEB_ACC_INGAME]    Script Date: 12.01.2021 14:39:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WEB_ACC_INGAME](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[uuid] [varchar](255) NOT NULL,
	[account] [varchar](50) NOT NULL,
	[state] [int] NULL,
	[create_date] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


